  
name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        ref: dev

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
        BASE_BRANCH: dev
        BRANCH: master
        FOLDER: docs/.vuepress/dist
        BUILD_SCRIPT: npm install && npm run docs:build